global:
  logLevel: info # pino log level
  contact: "https://plrm.adamski2003.lol/adam" # contact URL to be added to user-agent
outputs:
  - type: masto
    name: instance.tld
    options:
      token: "yourTokeHere"
      # logLevel: debug # log level override, works on any output
  - type: log
    name: logOutput
    options:
      logLevel: debug
directives:
  - instances:
      - instance1.tld
      - instance2.tld
    timelines:
      - $public:local
      - art:50:+watercolor
  - instances:
      - instance2.tld
      - instance3.tld
    timelines:
      - $public
      - science:80
users:
  - "@user@instance3.tld"
  - "@user2@instance4.tld"
